# kind-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 31289
        hostPort: 31289
        protocol: TCP
  - role: worker
  - role: worker