replicaCount: 2

image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent

containerPort: 80

service:
 type: NodePort
 port: 80
 nodePort: 30080

resources:
  requests:
    memory: "64Mi"
    cpu: "100m"
  limits:
    memory: "128Mi"
    cpu: "250m"
